# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-07 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("conferences", "0002_auto_20171121_0725")]

    operations = [
        migrations.AddField(
            model_name="conferenceregistration",
            name="products",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conferenceregistration",
            name="qbo_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
