# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("conferences", "0003_auto_20190307_1353")]

    operations = [
        migrations.AddField(
            model_name="conferenceregistration",
            name="is_group",
            field=models.BooleanField(default=False),
        )
    ]
