# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_conferenceregistration_is_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceEmailLogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceEmailRegistation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal registration"),
                            ("speaker", "Speaker registration"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceEmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField()),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal registration"),
                            ("speaker", "Speaker registration"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="conferenceinterface",
            name="api_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceinterface",
            name="private_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceinterface",
            name="url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="billing_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="billing_html",
            field=tinymce.models.HTMLField(default=""),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="conference_dinner",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="dinner_guest",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="email",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="organization",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="payment_type",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("wire", "Wire Transfer")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="product_html",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="conferenceregistration",
            name="reception_guest",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
