# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-05 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0005_auto_20201105_0541"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConferenceEmailRegistation",
            new_name="ConferenceEmailRegistration",
        ),
    ]
