# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20201105_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceemailregistration',
            name='email_type',
            field=models.CharField(choices=[('normal', 'Normal registration'), ('presenter', 'Presenter registration')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='conferenceemailtemplate',
            name='email_type',
            field=models.CharField(choices=[('normal', 'Normal registration'), ('presenter', 'Presenter registration')], default='normal', max_length=20),
        ),
    ]
