# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171121_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglog',
            name='invoice_year',
            field=models.CharField(default=b'2018', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.IntegerField(choices=[(4, b'Employee of'), (6, b'Lead Contact for'), (9, b'Certifier for'), (10, b'Voting Representative'), (11, b'Affiliated with'), (12, b'AC Member of'), (13, b'Accounting Contact')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_year',
            field=models.CharField(default=b'2018', max_length=10),
        ),
    ]
