# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20181001_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_type',
            field=models.CharField(choices=[(b'normal', b'Normal billing'), (b'consortia', b'Billed via Associate Consortia'), (b'custom', b'Custom Agreement'), (b'waiver', b'Fee waiver')], default=b'normal', max_length=128),
        ),
    ]
