# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")

    for org in Organization.objects.filter(associate_consortium__in=['TOCWC', 'JOCWC']):
        org.billing_type = 'consortia'
        org.save()

    # Taiwan Open Course and Education Consortium (TOCEC), Japan OCW Consortium
    for org in Organization.objects.filter(pk__in=[213, 370]):
        org.billing_type = 'custom'
        org.save()

    # Sustaining members
    for org in Organization.objects.filter(membership_status=7):
        org.billing_type = 'custom'
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0007_organization_billing_type'),
    ]

    operations = [
        migrations.RunPython(forwards, hints={'target_db': 'default'}),
    ]
