# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0009_fix_billing_year_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglog',
            name='invoice_year',
            field=models.CharField(default=b'2019', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_year',
            field=models.CharField(default=b'2019', max_length=10),
        ),
    ]
