# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    User = apps.get_model("auth", "User")

    for user in User.objects.all():
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_update_year_0408'),
    ]

    operations = [
        # Fixes our broken state of ContentType table
        migrations.RunSQL('ALTER TABLE django_content_type DROP COLUMN name;'),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_access_token', models.CharField(blank=True, default=b'', max_length=255)),
                ('qb_refresh_token', models.CharField(blank=True, default=b'', max_length=255)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards, hints={'target_db': 'default'}),
    ]
