# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-20 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0015_join_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_access_token', models.TextField(blank=True, default=b'')),
                ('qb_refresh_token', models.TextField(blank=True, default=b'')),
                ('qb_valid', models.BooleanField(default=False)),
                ('qb_token_expires', models.DateTimeField(default=None, null=True)),
                ('qb_refresh_expires', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
