# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qb_realm_id',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
