# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_profile_qb_realm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='crmid',
        ),
        migrations.AddField(
            model_name='organization',
            name='qbo_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
