# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-15 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0019_profile_qb_id")]

    operations = [
        migrations.AddField(
            model_name="billinglog",
            name="qbo_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="qbo_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
