# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 06:33
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")

    Organization.objects.filter(institution_type="primary-ed").update(
        institution_Type="secondary-ed"
    )
    Organization.objects.filter(institution_type="ngo").update(institution_Type="npo")
    Organization.objects.filter(institution_type="igo").update(institution_Type="npo")
    Organization.objects.filter(institution_type="igo").update(institution_Type="npo")
    Organization.objects.filter(institution_type="software").update(
        institution_Type="commercial"
    )


class Migration(migrations.Migration):

    dependencies = [("crm", "0025_auto_20190423_1122")]

    operations = []
