# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0026_new_categories")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.Country",
                verbose_name=b"Country/region",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="associate_consortium",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        b"CCCOER",
                        b"Community College Consortium for Open Educational Resources (CCCOER)",
                    ),
                    (b"CORE", b"CORE"),
                    (b"JOCWC", b"Japan OCW Consortium"),
                    (b"KOCWC", b"Korea OCW Consortium"),
                    (b"TOCEC", b"Taiwan Open Course and Education Consortium"),
                    (b"Turkish OCWC", b"Turkish OpenCourseWare Consortium"),
                    (b"UNIVERSIA", b"UNIVERSIA"),
                    (b"FOCW", b"Open Education France"),
                    (b"OTHER", b"OTHER"),
                ],
                default=b"",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"higher-ed", b"University"),
                    (b"secondary-ed", b"Primary and secondary (K-12)"),
                    (b"college", b"Community, technical, or vocational college"),
                    (b"non-accredited", b"Informal non-accredited education"),
                    (b"lifelong", b"Lifelong learning"),
                    (b"consortium", b"Consortia"),
                    (b"initiative", b"Open initiatives or special project"),
                    (b"commercial", b"Corporate enterprise"),
                    (b"npo", b"Non-profits, NGO\xe2\x80\x99s, IGO"),
                    (b"cultural", b"Cultural organization"),
                    (b"gov", b"Government"),
                ],
                default=b"",
                max_length=25,
                verbose_name=b"Institution Category",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"university", b"University"),
                    (b"npo", b"Non-Profit Organization"),
                    (b"ngo", b"Non-Governmental Organization"),
                    (b"regionalconsortium", b"Regional Consortium"),
                    (b"software", b"Software Development"),
                    (b"commercial", b"Commercial Entity"),
                ],
                default=b"",
                max_length=765,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="associate_consortium",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        b"CCCOER",
                        b"Community College Consortium for Open Educational Resources (CCCOER)",
                    ),
                    (b"CORE", b"CORE"),
                    (b"JOCWC", b"Japan OCW Consortium"),
                    (b"KOCWC", b"Korea OCW Consortium"),
                    (b"TOCEC", b"Taiwan Open Course and Education Consortium"),
                    (b"Turkish OCWC", b"Turkish OpenCourseWare Consortium"),
                    (b"UNIVERSIA", b"UNIVERSIA"),
                    (b"FOCW", b"Open Education France"),
                    (b"OTHER", b"OTHER"),
                ],
                default=b"",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"higher-ed", b"University"),
                    (b"secondary-ed", b"Primary and secondary (K-12)"),
                    (b"college", b"Community, technical, or vocational college"),
                    (b"non-accredited", b"Informal non-accredited education"),
                    (b"lifelong", b"Lifelong learning"),
                    (b"consortium", b"Consortia"),
                    (b"initiative", b"Open initiatives or special project"),
                    (b"commercial", b"Corporate enterprise"),
                    (b"npo", b"Non-profits, NGO\xe2\x80\x99s, IGO"),
                    (b"cultural", b"Cultural organization"),
                    (b"gov", b"Government"),
                ],
                default=b"",
                max_length=25,
            ),
        ),
    ]
