# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20200321_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('primary', 'Primary Address'), ('billing', 'Billing Address')], default='primary', max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Country', verbose_name='Country/region'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address with street number', max_length=255),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Created Date (year-month-day)'),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='email',
            field=models.CharField(blank=True, max_length=120, verbose_name='Recepient email'),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='email_body',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='email_subject',
            field=models.CharField(blank=True, max_length=140, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='invoice_year',
            field=models.CharField(default='2019', max_length=10),
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='log_type',
            field=models.CharField(choices=[('create_invoice', 'Invoice'), ('send_invoice', 'Send invoice via email'), ('create_paid_invoice', 'Create paid invoice'), ('send_paid_invoice', 'Send paid invoice via email'), ('create_note', 'Accounting note'), ('create_general_note', 'General note'), ('create_payment', 'Payment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.IntegerField(choices=[(4, 'Employee of'), (6, 'Lead Contact for'), (9, 'Certifier for'), (10, 'Voting Representative'), (11, 'Affiliated with'), (12, 'AC Member of'), (13, 'Accounting Contact')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Created Date (year-month-day)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('issued', 'Normal issued invoice'), ('paid', 'Invoice with paid watermark')], default='issued', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_year',
            field=models.CharField(default='2019', max_length=10),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='accreditation_body',
            field=models.CharField(blank=True, default='', max_length=765),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='app_status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Committee', 'Sent to Committee'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Spam', 'Spam'), ('RequestedMoreInfo', 'Requested more information')], max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='associate_consortium',
            field=models.CharField(blank=True, choices=[('CCCOER', 'Community College Consortium for Open Educational Resources (CCCOER)'), ('CORE', 'CORE'), ('JOCWC', 'OE Japan'), ('KOCWC', 'Korea OCW Consortium'), ('TOCEC', 'Taiwan Open Course and Education Consortium'), ('Turkish OCWC', 'Turkish OpenCourseWare Consortium'), ('UNIVERSIA', 'UNIVERSIA'), ('FOCW', 'Open Education France'), ('OTHER', 'OTHER')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='corporate_support_levels',
            field=models.CharField(blank=True, choices=[('basic', 'Basic - $1,000 annual membership fee'), ('sustaining', 'Sustaining - $30,000 contribution annual membership fee'), ('bronze', 'Bronze - $60,000 contribution annual membership fee'), ('silver', 'Silver - $100,000 contribution annual membership fee'), ('gold', 'Gold - $150,000 contribution annual membership fee'), ('platinum', 'Platinum - $250,000 contribution annual membership fee')], max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='description',
            field=models.TextField(blank=True, help_text='This information will be publicly displayed on your OEG profile site.'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_description1',
            field=models.TextField(blank=True, default='', verbose_name='Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_description2',
            field=models.TextField(blank=True, default='', verbose_name='Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_description3',
            field=models.TextField(blank=True, default='', verbose_name='Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_title1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_title2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_title3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_url1',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_url2',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='initiative_url3',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('secondary-ed', 'Primary and secondary (K-12)'), ('college', 'Community, technical, or vocational college'), ('higher-ed', 'University'), ('non-accredited', 'Informal non-accredited education'), ('lifelong', 'Lifelong learning'), ('consortium', 'Consortia Member'), ('consortium-org', 'Consortia Organization'), ('initiative', 'Open initiatives or special project'), ('commercial', 'Corporate enterprise'), ('npo', 'Non-profits, NGO’s, IGO'), ('cultural', 'Cultural organization'), ('gov', 'Government')], default='', max_length=25, verbose_name='Institution Category'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='is_accredited',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='logo_large',
            field=models.ImageField(blank=True, max_length=765, upload_to='logos', verbose_name='Submit an institution logo. Must be at least 500x500 pixels in a PNG, PDF, EPS, or JPG format.'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='membership_type',
            field=models.IntegerField(blank=True, choices=[(5, 'Institutional Members'), (10, 'Institutional Members - MRC'), (11, 'Institutional Members - DC'), (12, 'Institutional Members - DC - MRC'), (9, 'Associate Institutional Members'), (17, 'Associate Institutional Members - DC'), (6, 'Organizational Members'), (13, 'Organizational Members - DC'), (18, 'Organizational Members - MRC'), (7, 'Associate Consortium Members'), (14, 'Associate Consortium Members - DC'), (8, 'Corporate Members - Basic'), (15, 'Corporate Members - Premium'), (16, 'Corporate Members - Sustaining')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Should be empty, unless application is approved', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Organization'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('npo', 'Non-Profit Organization'), ('ngo', 'Non-Governmental Organization'), ('regionalconsortium', 'Regional Consortium'), ('software', 'Software Development'), ('commercial', 'Commercial Entity')], default='', max_length=765),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='simplified_membership_type',
            field=models.CharField(blank=True, choices=[('institutional', 'Institutional Member'), ('associate', 'Associate Consortium Member'), ('organizational', 'Organizational Member'), ('corporate', 'Corporate Member')], max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address with a street number', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='accreditation_body',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='associate_consortium',
            field=models.CharField(blank=True, choices=[('CCCOER', 'Community College Consortium for Open Educational Resources (CCCOER)'), ('CORE', 'CORE'), ('JOCWC', 'OE Japan'), ('KOCWC', 'Korea OCW Consortium'), ('TOCEC', 'Taiwan Open Course and Education Consortium'), ('Turkish OCWC', 'Turkish OpenCourseWare Consortium'), ('UNIVERSIA', 'UNIVERSIA'), ('FOCW', 'Open Education France'), ('OTHER', 'OTHER')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_type',
            field=models.CharField(choices=[('normal', 'Normal billing'), ('consortia', 'Billed via Associate Consortia'), ('custom', 'Custom Agreement'), ('waiver', 'Fee waiver')], default='normal', max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Name of the organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_description1',
            field=models.TextField(blank=True, default='', verbose_name='Initiative 1 Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_description2',
            field=models.TextField(blank=True, default='', verbose_name='Initiative 2 Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_description3',
            field=models.TextField(blank=True, default='', verbose_name='Initiative 3 Description (100 – 350 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_title1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Initiative 1 Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_title2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Initiative 2 Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_title3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Initiative 3 Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_url1',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Initiative 1 URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_url2',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Initiative 2 URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initiative_url3',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Initiative 3 URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('secondary-ed', 'Primary and secondary (K-12)'), ('college', 'Community, technical, or vocational college'), ('higher-ed', 'University'), ('non-accredited', 'Informal non-accredited education'), ('lifelong', 'Lifelong learning'), ('consortium', 'Consortia Member'), ('consortium-org', 'Consortia Organization'), ('initiative', 'Open initiatives or special project'), ('commercial', 'Corporate enterprise'), ('npo', 'Non-profits, NGO’s, IGO'), ('cultural', 'Cultural organization'), ('gov', 'Government')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_large',
            field=models.ImageField(blank=True, max_length=255, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_small',
            field=models.ImageField(blank=True, max_length=255, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='membership_status',
            field=models.IntegerField(choices=[(1, 'Applied'), (2, 'Current'), (3, 'Grace'), (4, 'Expired'), (5, 'Pending'), (6, 'Cancelled'), (7, 'Sustaining'), (99, 'Example')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='membership_type',
            field=models.IntegerField(choices=[(5, 'Institutional Members'), (10, 'Institutional Members - MRC'), (11, 'Institutional Members - DC'), (12, 'Institutional Members - DC - MRC'), (9, 'Associate Institutional Members'), (17, 'Associate Institutional Members - DC'), (6, 'Organizational Members'), (13, 'Organizational Members - DC'), (18, 'Organizational Members - MRC'), (7, 'Associate Consortium Members'), (14, 'Associate Consortium Members - DC'), (8, 'Corporate Members - Basic'), (15, 'Corporate Members - Premium'), (16, 'Corporate Members - Sustaining')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ocw_website',
            field=models.TextField(blank=True, max_length=255, verbose_name='OER/OCW Website'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='support_commitment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb_realm_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
