# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 13:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20190116_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='expertise',
            field=models.TextField(blank=True, default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
