# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20190116_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='expertise_expanded',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
