# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-17 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_expertise_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='agreement_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='agreement_fund',
            field=models.BooleanField(default=False),
        ),
    ]
