# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 04:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20190117_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email_alternate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expertise',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expertise_expanded',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expertise_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='external_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seat_type',
            field=models.CharField(blank=True, choices=[('institutional', 'Institutional'), ('organizational', 'Organizational')], max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('nominated', 'Nominated'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidateballot',
            name='seat_type',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('organizational', 'Organizational')], max_length=60),
        ),
        migrations.AlterField(
            model_name='propositionballot',
            name='vote',
            field=models.NullBooleanField(choices=[(True, 'We vote <strong>for</strong> this proposition'), (False, 'We vote <strong>against</strong> this proposition'), (None, 'We abstain')]),
        ),
    ]
